M48
; DRILL file KiCad 10.0.6 date 2026-09-11T22:25:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-11T22:25:59+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X53.11Y5.605
X58.89Y5.605
T2
X4.0Y46.0
X39.0Y4.0
X61.0Y25.0
M30
